stages:
  - setup
  - test
  - deploy

setup:
  image: composer:2
  stage: setup
  script:
    - composer install
  cache:
    paths:
      - vendor/

test:
  image: php:8.1
  stage: test
  before_script:
    - apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev libzip-dev zip unzip
    - docker-php-ext-install pdo_mysql zip
    - cp .env.example .env
    - php artisan key:generate
    - php artisan migrate --seed
  script:
    - vendor/bin/phpunit --testdox

deploy:
  stage: deploy
  script:
    - echo "Deploying your Laravel application..."
